#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# genomeBin CAS upload — push staged binaries to NestGate CAS
#
# Reads the stage/ directory (output of harvest.sh) and uploads each
# binary to NestGate via JSON-RPC `storage.store_blob`. Content is
# addressed by BLAKE3 hash. Generates a cas-manifest.toml for
# sporePrint compatibility and cross-gate replication.
#
# Prerequisites:
#   - NestGate running with UDS socket accessible
#   - harvest.sh completed (stage/ populated)
#   - b3sum installed (BLAKE3 checksums)
#
# Usage:
#   ./genomeBin/cas-upload.sh [--target x86_64-unknown-linux-gnu] [--dry-run]
#   ./genomeBin/cas-upload.sh --socket /run/user/1000/biomeos/nestgate.sock
#
# Evolution: bash (now) → nucleus-deploy cas-upload (Rust)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
STAGE_DIR="$SCRIPT_DIR/stage"
TARGET="${TARGET:-x86_64-unknown-linux-gnu}"
DRY_RUN=false
FAMILY_ID="${FAMILY_ID:-irongate-sovereign}"
NAMESPACE="genomeBin"

# NestGate socket resolution (same chain as primals)
NESTGATE_SOCKET="${NESTGATE_SOCKET:-}"
if [[ -z "$NESTGATE_SOCKET" ]]; then
    XDG="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
    for candidate in \
        "$XDG/biomeos/nestgate.sock" \
        "$XDG/biomeos/nestgate-${FAMILY_ID}.sock" \
        "/var/run/biomeos/nestgate.sock" \
        "/tmp/nestgate.sock"; do
        if [[ -S "$candidate" ]]; then
            NESTGATE_SOCKET="$candidate"
            break
        fi
    done
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        --target) TARGET="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        --socket) NESTGATE_SOCKET="$2"; shift 2 ;;
        --family-id) FAMILY_ID="$2"; shift 2 ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'
log() { echo -e "${GREEN}[cas-upload]${NC} $*"; }
err() { echo -e "${RED}[cas-upload]${NC} $*" >&2; }

OUTDIR="$STAGE_DIR/$TARGET"
if [[ ! -d "$OUTDIR" ]]; then
    err "Stage directory not found: $OUTDIR"
    err "Run harvest.sh first."
    exit 1
fi

MANIFEST="$STAGE_DIR/cas-manifest.toml"
UPLOADED=0
FAILED=0
SKIPPED=0

log "CAS upload — $TARGET"
log "Socket: ${NESTGATE_SOCKET:-NOT FOUND}"
log "Family: $FAMILY_ID"
log "Namespace: $NAMESPACE"
echo

# Generate cas-manifest header
{
    echo "# genomeBin CAS Manifest — auto-generated by cas-upload.sh"
    echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    echo "[manifest]"
    echo "target = \"$TARGET\""
    echo "family_id = \"$FAMILY_ID\""
    echo "namespace = \"$NAMESPACE\""
    echo ""
} > "$MANIFEST"

for binary in "$OUTDIR"/*; do
    [[ -f "$binary" ]] || continue
    name=$(basename "$binary")

    # Skip checksum files
    case "$name" in
        *.b3|*.sha256) continue ;;
    esac

    # Compute BLAKE3 hash
    if command -v b3sum >/dev/null 2>&1; then
        hash=$(b3sum "$binary" | awk '{print $1}')
    else
        hash=$(sha256sum "$binary" | awk '{print $1}')
        log "  WARN: b3sum not found, using SHA-256 for $name"
    fi

    size=$(stat -c%s "$binary" 2>/dev/null || stat -f%z "$binary" 2>/dev/null)
    cas_key="$NAMESPACE/$TARGET/$name/$hash"

    log "Uploading $name ($size bytes, hash=$hash)"

    if $DRY_RUN; then
        log "  [dry-run] → $cas_key"
        UPLOADED=$((UPLOADED + 1))
    elif [[ -z "$NESTGATE_SOCKET" ]]; then
        log "  SKIP — no NestGate socket found"
        SKIPPED=$((SKIPPED + 1))
    else
        # Base64 encode the binary for JSON-RPC transport
        blob_b64=$(base64 -w0 "$binary")

        payload=$(cat <<JSONRPC
{"jsonrpc":"2.0","method":"storage.store_blob","params":{"key":"$cas_key","blob":"$blob_b64","family_id":"$FAMILY_ID","namespace":"$NAMESPACE"},"id":1}
JSONRPC
)
        response=$(echo "$payload" | socat - UNIX-CONNECT:"$NESTGATE_SOCKET" 2>&1) || true

        if echo "$response" | grep -q '"stored"'; then
            log "  OK → $cas_key"
            UPLOADED=$((UPLOADED + 1))
        else
            err "  FAIL — $name: $response"
            FAILED=$((FAILED + 1))
        fi
    fi

    # Append to cas-manifest
    {
        echo "[[binaries]]"
        echo "name = \"$name\""
        echo "hash = \"$hash\""
        echo "size = $size"
        echo "cas_key = \"$cas_key\""
        echo ""
    } >> "$MANIFEST"
done

echo
log "Upload complete: $UPLOADED OK, $FAILED FAIL, $SKIPPED SKIP"
log "Manifest: $MANIFEST"

if [[ $FAILED -gt 0 ]]; then
    exit 1
fi
